### PR TITLE
Added BERT Model

### PR DESCRIPTION
**Pull request by adi271001**
Issue #5

### CODE REVIEW

**Comment by AyushTripathiIITP** [comment]
great job @adi271001

**Comment by adi271001** [comment]
@AyushTripathiIITP please do assign the codepeaks tag

**Comment by adi271001** [comment]
@AyushTripathiIITP also i don't think this has been merged not able to see my files here

**Comment by AyushTripathiIITP** [comment]
I am checking your PR against Plagiarism I will merge it after that.

**Pull request closed without merging**
